import { Schema, type Types } from "mongoose";

export const ObjectId = Schema.Types.ObjectId;
export type ObjectIdType = Types.ObjectId;

export const Categories = [
  "Consumer Electronics",
  "Mobile phones",
  "Laptops",
  "Televisions",
  "Speakers",
  "Routers",
  "Printers",
  "Tablets",
  "Mobile Subparts",
  "Displays",
  "Batteries",
  "IC chips",
  "Charging ports",
  "Microphones",
  "Camera modules",
  "Computer Components",
  "Motherboards",
  "RAM",
  "SSD",
  "GPU",
  "Power supplies",
  "Keyboards",
  "Mouse",
  "Electrical Items",
  "LED bulbs",
  "Switches",
  "Wires",
  "Sockets",
  "Extension boards",
  "Small Electronic Components",
  "Resistors",
  "Capacitors",
  "Transistors",
  "Microcontrollers",
  "Drone Parts",
  "Frames",
  "Propellers",
  "Motors",
  "ESC",
  "Flight controllers",
  "GPS modules",
  "Air Conditioner Parts",
  "Compressors",
  "PCB boards",
  "Sensors",
  "Fan motors",
  "Industrial Electronics",
  "Relays",
  "Transformers",
  "PLC modules",
  "Voltage regulators",
  "Tools & Testing Equipment",
  "Multimeters",
  "Soldering stations",
  "Repair kits"
] as const;

